<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
require_once 'includes/auth.php';
$auth = new Auth();
if (!$auth->isLoggedIn()) {
    header("Location: login.php");
    exit;
}
$username = $_SESSION['username'];
?>
<!DOCTYPE html>
<html lang="no">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Statistikk - MindMatrix</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="hexagon-background" id="hexagon-container"></div>

    <?php include 'includes/header.php'; ?>

    <main class="main-container">
        <div class="content-section">
            <h1 class="content-title">Din Statistikk</h1>
            
            <div class="stats-grid" style="margin-bottom: 3rem;">
                <div class="stat-card">
                    <div class="stat-value">47</div>
                    <div class="stat-label">Totalt Spill</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">8,924</div>
                    <div class="stat-label">Totale Poeng</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">12</div>
                    <div class="stat-label">Dager i Rekke</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">76%</div>
                    <div class="stat-label">Gjennomsnitt</div>
                </div>
            </div>

            <h2 class="content-subtitle">Prestasjon per Spill</h2>
            <p style="text-align: center; color: var(--text-secondary); margin-bottom: 2rem;">
                Klikk på et spill for å se detaljert statistikk og utvikling over tid
            </p>
            
            <div class="hexagon-chart-container">
                <div id="hexagonChart" class="hexagon-chart">
                    <!-- Hexagon chart will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </main>

    <?php include 'includes/footer.php'; ?>
    <script src="script.js"></script>
</body>
</html>